bool_true = True
bool_false = False
string = "string"
zero_string = ""
my_int_float = 1
zero = 0
my_list = [0]
zero_list = []
my_tuple = 0,
zero_tuple = tuple()
my_set = {0}
zero_set = set()
my_dict = {0:0}
zero_dict = {}
print('bool_true -', bool(bool_true))
print('bool_false -', bool(bool_false))
print('string -', bool(string))
print('zero_string -', bool(zero_string))
print('my_int_float -', bool(my_int_float))
print('zero -', bool(zero))
print('my_list -', bool(my_list))
print('zero_list -', bool(zero_list))
print('my_tuple -', bool(my_tuple))
print('zero_tuple -', bool(zero_tuple))
print('my_set -', bool(my_set))
print('zero_set -', bool(zero_set))
print('my_dict -', bool(my_dict))
print('zero_dict -', bool(zero_dict))